# Generated by Django 4.0.1 on 2022-04-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_user_id_product_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userid',
        ),
    ]
